importing contribs/tzdataexport.py from xivo-utils
wazo-platform/wazo-provd pull request #62
Opened 2023-01-19 14:26 UTC by DrPyser

2023-01-19 18:34 UTC, pc-m requested changes
Can you add some info in the readme on how to use this script?

2023-01-19 18:34 UTC, pc-m commented on contribs/tzdataexport.py
> +__version__ = "$Revision$ $Date$"
You can remove the `__version__` variable, the values are not substituted by the current build system and it is unused

2023-01-19 18:39 UTC, DrPyser commented
https://github.com/search?q=org%3Awazo-platform+tzinform&type=code

tzinform uses the tzdatax file. provd.tzinform is used mostly in provd plugins. Updating that configuration would probably affect timezones management in supported phone devices.

2023-01-19 20:18 UTC, fblackburn1 commented
FYI This change is more an archive commit than rebuild/fix the thing.
Currently this script was shipped (but not used) in the wazo and the only occurrence was in the outdated tz db from provd
This whole DB should be investigated to be completely removed as state in https://wazo-dev.atlassian.net/browse/WAZO-3021

2023-01-23 18:12 UTC, DrPyser commented
> FYI This change is more an archive commit than rebuild/fix the thing. Currently this script was shipped (but not used) in the wazo and the only occurrence was in the outdated tz db from provd This whole DB should be investigated to be completely removed as state in https://wazo-dev.atlassian.net/browse/WAZO-3021

Are you propositing this could be merged without documentation/extensive testing(I did test the main codepath of running the script with a valid input, and getting an output, but I was going to try and set up a test case for applying the new output to provd)? I understand if the plan is to trash and rewrite before using it anyway.

2023-01-31 15:06 UTC, fblackburn1 approved these changes

2023-01-31 15:15 UTC, fblackburn1 commented
regate

2023-01-31 15:22 UTC, merged